apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-descheduler
  namespace: openshift-kube-descheduler-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - exported_namespace
      targetLabel: pod_namespace
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: metrics.openshift-kube-descheduler-operator.svc
  namespaceSelector:
    matchNames:
    - openshift-kube-descheduler-operator
  selector:
    matchLabels:
      app: descheduler
